// AUTO-GENERATED by scripts/sync-contracts.mjs — do not edit.
// Edit the file listed on the line below and rerun the script.
// Source: shared/contracts/http/decrypted-messages/types.ts

// Dependency-free TypeScript interfaces for POST /decrypted-messages.
// Web imports types only (no zod); gateway and the Supabase Edge Function
// import protocol.ts alongside.
// DO NOT import any library from this file.

/**
 * M3 Unified history endpoint.
 *
 * Owner, Agent, and Visitor all call the same Edge Function. `actor`
 * discriminates the auth path:
 *   - 'owner'   — Authorization: Bearer <supabase-jwt>; RLS chain verifies
 *                 owner owns conversation.
 *   - 'agent'   — Authorization: Bearer <agent-api-key>; api_key_hash maps
 *                 to agents.id; agent must own conversation.qrcode.
 *   - 'visitor' — No Authorization header. `session_token` in body MUST
 *                 match conversations.session_token for the given
 *                 conversation_id (anti-enumeration guard).
 *
 * The Edge Function decrypts content in-memory with QRCLAW_KEK_V1 → DEK
 * envelope. Individual message failures yield the sentinel
 * `[decryption_failed]` so one bad row cannot block the whole page.
 */

export const DECRYPTED_ACTORS = ['owner', 'agent', 'visitor', 'owner-private-agent-chat'] as const;
export type DecryptedActor = (typeof DECRYPTED_ACTORS)[number];

export const DECRYPTED_MESSAGES_LIMIT_MIN = 1;
export const DECRYPTED_MESSAGES_LIMIT_MAX = 100;
export const DECRYPTED_MESSAGES_LIMIT_DEFAULT = 50;

export const DECRYPTION_FAILED_SENTINEL = '[decryption_failed]';
export const DECRYPTION_UNAVAILABLE_SENTINEL = '[decryption_unavailable]';

export interface DecryptedMessagesBaseRequest {
  conversation_id: string; // UUID
  cursor?: string; // messages.id to page before
  limit?: number; // default DEFAULT, clamped to [MIN, MAX]
}

export interface DecryptedMessagesOwnerRequest extends DecryptedMessagesBaseRequest {
  actor: 'owner';
}

export interface DecryptedMessagesAgentRequest extends DecryptedMessagesBaseRequest {
  actor: 'agent';
}

export interface DecryptedMessagesVisitorRequest extends DecryptedMessagesBaseRequest {
  actor: 'visitor';
  session_token: string;
}

export interface DecryptedOwnerPrivateAgentChatRequest extends DecryptedMessagesBaseRequest {
  actor: 'owner-private-agent-chat';
  include_events?: boolean;
  run_id?: string; // UUID
  after_seq?: number; // Return run events with seq > after_seq
}

export type DecryptedMessagesRequest =
  | DecryptedMessagesOwnerRequest
  | DecryptedMessagesAgentRequest
  | DecryptedMessagesVisitorRequest
  | DecryptedOwnerPrivateAgentChatRequest;

/** messages.role column values the platform persists. */
export const MESSAGE_ROLES = ['visitor', 'agent', 'owner', 'system'] as const;
export type MessageRole = (typeof MESSAGE_ROLES)[number];

/**
 * Single decrypted message row.
 *
 * Fields nullable on legacy rows that predate M1 thread pre-provisioning:
 *   - reply_to_message_id
 *   - thread_id
 */
export interface DecryptedMessage {
  id: string; // messages.id or owner_agent_messages.id
  message_id: string; // messages.message_id, or owner_agent_messages.id for owner-private rows
  content: string; // plaintext or `[decryption_failed]` sentinel
  sender_type: MessageRole; // aka `role` / owner_agent_messages.sender_type
  persisted_at: string; // ISO 8601 (messages.sent_at / owner_agent_messages.created_at)
  run_id?: string | null;
  content_type?: string;
  status?: string;
  reply_to_message_id?: string | null;
  thread_id?: string | null;
}

export interface DecryptedOwnerAgentRunEvent {
  id: string;
  run_id: string;
  seq: number;
  type: string;
  content: string | null;
  metadata: Record<string, unknown>;
  persisted_at: string;
}

export interface DecryptedMessagesResponse {
  data: DecryptedMessage[];
  events?: DecryptedOwnerAgentRunEvent[];
  meta: {
    cursor: string | null; // next-page token (messages.id); null at end
    has_more: boolean;
    event_cursor?: number | null; // last returned owner_agent_run_events.seq
  };
}

/**
 * Canonical error codes emitted by the Edge Function.
 * Web and gateway should switch on these for user-facing mapping.
 */
export const DECRYPTED_ERROR_CODES = [
  'invalid_request',
  'invalid_cursor',
  'unauthorized',
  'forbidden',
  'not_found',
  'encryption_error',
  'method_not_allowed',
  'internal_error',
] as const;
export type DecryptedErrorCode = (typeof DECRYPTED_ERROR_CODES)[number];
