/**
 * Security Envelope injection for outbound messages.
 * Per §10.2-10.6: Every agent→visitor message must carry a security envelope
 * declaring the platform's content policy, enabling client-side enforcement.
 *
 * Iron Rule C1: Gateway is a pure relay — the envelope declares policy,
 * it does NOT filter or modify message content.
 */
import { createHash } from 'crypto';
import type { SecurityEnvelope } from '../types/index.js';

// ─── Policy Configuration ───────────────────────────────────────────

const POLICY_VERSION = '1.0';

const POLICY_RULES = [
  'ai_generated_disclosure',
  'no_medical_legal_financial_advice',
  'content_source_attribution',
  'user_data_handling_notice',
] as const;

const ENFORCEMENT_TEXT =
  'This message was generated by an AI agent. Content is for informational purposes only ' +
  'and should not be considered professional advice. The platform stores messages for ' +
  'synchronization but does not analyze message content.';

// Compute policy hash once at module load (deterministic)
const POLICY_HASH = createHash('sha256')
  .update(POLICY_VERSION + POLICY_RULES.join(',') + ENFORCEMENT_TEXT)
  .digest('hex')
  .slice(0, 16);

const POLICY_ID = `qrclaw-policy-${POLICY_VERSION}`;

// ─── Envelope Creation ──────────────────────────────────────────────

/**
 * Create a SecurityEnvelope for an outbound agent message.
 * Called by the router before forwarding agent→visitor messages.
 */
export const createSecurityEnvelope = (): SecurityEnvelope => ({
  version: POLICY_VERSION,
  policy_id: POLICY_ID,
  policy_hash: POLICY_HASH,
  rules: [...POLICY_RULES],
  enforcement_text: ENFORCEMENT_TEXT,
  injected_at: new Date().toISOString(),
});

/**
 * Inject a security envelope into an outbound message frame payload.
 * Returns a new payload object (immutable — original is not mutated).
 *
 * The generic `T` preserves the caller's payload shape through the envelope
 * injection so emit sites (router.ts message + stream_end) can construct
 * well-typed `MessageFrame` / `StreamEndFrame` values without widening to
 * `Record<string, unknown>` and re-casting (T3d).
 */
export const injectSecurityEnvelope = <T extends Record<string, unknown>>(
  payload: T
): T & { security_envelope: SecurityEnvelope } => ({
  ...payload,
  security_envelope: createSecurityEnvelope(),
});
