// AUTO-GENERATED by scripts/sync-contracts.mjs — do not edit.
// Edit the file listed on the line below and rerun the script.
// Source: shared/contracts/ws/types.ts

// Dependency-free TypeScript interfaces for QRClaw WebSocket frames.
// Consumed by web (pure types), gateway (alongside protocol.ts), and
// supabase functions (via the sync-contracts.mjs generated copy).
// DO NOT import any library from this file — Deno/bundler safety.

export interface WSFrame {
  type: string;
  id?: string;
  timestamp: string;
  payload?: Record<string, unknown>;
}

export const OWNER_AGENT_WS_PROVIDERS = ['openclaw', 'claude', 'cursor', 'codex', 'pi'] as const;
export type OwnerAgentWsProvider = (typeof OWNER_AGENT_WS_PROVIDERS)[number];

export const OWNER_AGENT_WS_RUN_EVENT_TYPES = [
  'text',
  'status',
  'error',
  'tool_use',
  'tool_result',
  'thinking',
] as const;
export type OwnerAgentWsRunEventType = (typeof OWNER_AGENT_WS_RUN_EVENT_TYPES)[number];

export const OWNER_AGENT_WS_PROVIDER_STATUSES = [
  'not_installed',
  'needs_login',
  'online',
  'offline',
  'error',
  'available',
  'unavailable',
  'version_unsupported',
] as const;
export type OwnerAgentWsProviderStatus = (typeof OWNER_AGENT_WS_PROVIDER_STATUSES)[number];

// ─── Client → Gateway ────────────────────────────────────────────────

// Ping/auth/read_receipt are idless control frames — gateway schemas do not
// accept `id` on them (`.strict()` rejects extras), so we Omit WSFrame.id
// here to keep z.infer<schema> === hand-written type parity.
export interface PingFrame extends Omit<WSFrame, 'id'> {
  type: 'ping';
  payload?: Record<string, never>;
}

// Visitor 端不支持 reply_to_message_id / thread_id —— 移动端 MVP 仅线性聊天，
// 群聊/话题语义只在 agent → visitor 方向（agent_message + outbound message）预留。
export interface VisitorMessageFrame extends WSFrame {
  type: 'visitor_message';
  id: string;
  payload: {
    content: string;
    content_type: 'text' | 'image_url' | 'file_url';
    metadata?: Record<string, unknown>;
  };
}

export interface AgentMessageFrame extends WSFrame {
  type: 'agent_message';
  id: string;
  payload: {
    content: string;
    content_type: 'text' | 'markdown' | 'image_url' | 'file_url';
    conversation_id: string;
    is_final?: boolean;
    metadata?: Record<string, unknown>;
    // 以下两个 optional 字段为 MVP 阶段架构预留，始终 undefined。
    // 启用条件：群聊 / 话题特性立项后由 agent 端按 plan §5.1 L1.6 + M1-DB-RESERVE 写入。
    reply_to_message_id?: string;
    thread_id?: string;
  };
}

export interface StreamChunkFrame extends WSFrame {
  type: 'stream_chunk';
  id: string;
  payload: {
    conversation_id: string;
    delta: string;
    sequence?: number;
    is_final?: boolean;
  };
}

export interface StreamEndFrame extends WSFrame {
  type: 'stream_end';
  id: string;
  payload: {
    conversation_id: string;
    total_chunks?: number;
    total_length?: number;
    full_content?: string;
    // D3 (Phase 2 Wave 2) — `router.ts:502` injects a SecurityEnvelope on
    // the final forwarded stream_end frame. Absent on the plain forward
    // fallback path (`router.ts:420–430`).
    security_envelope?: SecurityEnvelope;
  };
}

export interface ReadReceiptFrame extends Omit<WSFrame, 'id'> {
  type: 'read_receipt';
  payload: {
    message_ids: string[];
  };
}

export interface AuthFrame extends Omit<WSFrame, 'id'> {
  type: 'auth';
  payload: {
    ticket: string;
    session_token?: string;
  };
}

// ─── Security Envelope (Gateway → Client policy metadata) ───────────
//
// Injected by `gateway/src/ws/security-envelope.ts` into outbound
// `message` and `stream_end` payloads (see §10.2-10.6). Moved from
// `gateway/src/types/index.ts` in Phase 2 Wave 2 so the shared outbound
// Zod barrel (`ws/outbound.ts`) and any future cross-runtime consumer
// (web type-level, supabase generated mirror) can reference a single
// source of truth. `gateway/src/types/index.ts` keeps a re-export shim
// to avoid churning gateway import sites.

export interface SecurityEnvelope {
  version: string;
  policy_id: string;
  policy_hash: string;
  rules: string[];
  enforcement_text: string;
  injected_at: string;
}

// ─── Gateway → Client ────────────────────────────────────────────────

export interface ConnectionAckFrame extends WSFrame {
  type: 'connection_ack';
  payload: {
    connection_id: string;
    heartbeat_interval_ms: number;
    server_time?: string;
  };
}

// `ACK_STATUSES` enumerates every status the Gateway actually emits.
// Phase 2 Wave 2 D5 widened this from `'sent'|'delivered'|'read'|'failed'`
// to include the router's real-world strings (`'accepted'`, `'duplicate'`,
// `'rejected:*'`). Kept as a `const` tuple (same pattern as
// `INBOUND_FRAME_TYPES` below) so the Zod side (`ws/outbound.ts`) and
// parity tests can consume a single source of truth without manual
// enum re-typing — add a value here and every downstream site picks it
// up. The Zod `z.enum([...])` mirror intentionally rejects any other
// value (no passthrough) so drift surfaces immediately.
export const ACK_STATUSES = [
  'sent',
  'delivered',
  'read',
  'failed',
  'accepted',
  'duplicate',
  'rejected:invalid_session',
  'rejected:agent_unreachable',
  'rejected:rate_limited',
] as const;

export type AckStatus = (typeof ACK_STATUSES)[number];

export interface AckFrame extends WSFrame {
  type: 'ack';
  payload: {
    message_id: string;
    status: AckStatus;
    error_code?: string;
    error_message?: string;
  };
}

// 注意：MessageFrame 是 Gateway → Client 下行帧。Phase 2 Wave 2 在
// `shared/contracts/ws/outbound.ts` 里加了 outbound Zod schema 和
// `validateOutboundFrame`，绑定 emit 点；历史 TS-only 的约束不再是唯一保险。
export interface MessageFrame extends WSFrame {
  type: 'message';
  id: string;
  payload: {
    content: string;
    content_type: 'text' | 'markdown' | 'image_url' | 'file_url';
    sender_type: 'visitor' | 'agent';
    conversation_id: string;
    // 以下两个 optional 字段为 MVP 阶段架构预留，始终 undefined。
    // 启用条件：群聊 / 话题特性立项后由 Gateway 端按 plan §5.1 L1.6 + M1-DB-RESERVE 写入。
    reply_to_message_id?: string;
    thread_id?: string;
    // D2 (Phase 2 Wave 2) — injected by `injectSecurityEnvelope()` on
    // agent→visitor forwards. Absent on offline-queue drain frames.
    security_envelope?: SecurityEnvelope;
    // D4 (Phase 2 Wave 2) — set only on offline-queue drain emissions
    // (`handler.ts` during agent reconnect), ISO timestamp of the queue
    // moment. Absent on live-forward frames.
    queued_at?: string;
  };
}

// D1 (Phase 2 Wave 2) — Gateway→agent broadcast shape for visitor messages.
// Distinct from the inbound `VisitorMessageFrame` because the broadcast
// carries gateway-only fields (`sender_type`, `conversation_id`,
// `qr_code_id`, optional `system_prompt`) that must never appear on the
// inbound schema. Emitted by `router.ts:203–218`.
export interface VisitorMessageBroadcastFrame extends WSFrame {
  type: 'visitor_message';
  id: string;
  payload: {
    content: string;
    content_type: 'text' | 'image_url' | 'file_url';
    sender_type: 'visitor';
    conversation_id: string;
    qr_code_id?: string;
    system_prompt?: string;
    // Forward-compat: same rationale as `MessageFrame` / `AgentMessageFrame`.
    reply_to_message_id?: string;
    thread_id?: string;
  };
}

export interface AgentTypingFrame extends WSFrame {
  type: 'agent_typing';
  payload: {
    conversation_id: string;
  };
}

export interface PongFrame extends WSFrame {
  type: 'pong';
}

// ErrorFrame.payload.code stays typed as plain `string` intentionally —
// the Zod outbound schema (`ws/outbound.ts`) is the single source of
// truth for the closed enum. Keeping TS wide lets future gateway
// codepaths introduce new codes without a type-level break (Zod will
// still reject them at runtime until the enum is extended).
export interface ErrorFrame extends WSFrame {
  type: 'error';
  payload: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
    // D6 (Phase 2 Wave 2) — router.ts:389 attaches the offending frame
    // id to routing_error responses so clients can correlate the error
    // with the request they sent.
    message_id?: string;
  };
}

export interface SystemFrame extends WSFrame {
  type: 'system';
  payload: {
    event:
      | 'agent_online'
      | 'agent_offline'
      | 'qrcode_paused'
      | 'qrcode_activated'
      | 'session_expired';
    data?: Record<string, unknown>;
  };
}

// ─── Owner Agent Chat Host + Run Frames ───────────────────────────────

export interface HostProviderCapability {
  provider: OwnerAgentWsProvider;
  version: string | null;
  status: OwnerAgentWsProviderStatus;
  binary_path?: string | null;
  capabilities: {
    streaming: boolean;
    full_access: boolean;
    models?: string[];
  };
}

export interface HostRegisterFrame extends WSFrame {
  type: 'host_register';
  payload: {
    host_id: string;
    host_type: 'local' | 'cloud';
    display_name: string;
    providers: HostProviderCapability[];
    in_flight_runs?: {
      run_id: string;
      last_seq: number;
      status: 'accepted' | 'running';
    }[];
  };
}

export interface HostHeartbeatFrame extends WSFrame {
  type: 'host_heartbeat';
  payload: {
    host_id: string;
    active_run_ids?: string[];
  };
}

export interface HostCapabilitiesUpdatedFrame extends WSFrame {
  type: 'host_capabilities_updated';
  payload: {
    host_id: string;
    providers: HostProviderCapability[];
  };
}

export type OwnerAgentRunPayloadBase = {
  run_id: string;
  conversation_id: string;
  agent_id: string;
  provider: OwnerAgentWsProvider;
  correlation_id: string;
};

export interface OwnerAgentRunRequestFrame extends WSFrame {
  type: 'owner_agent_run_request';
  payload: OwnerAgentRunPayloadBase & {
    owner_message_id: string;
    content: string;
    content_type: 'text';
    instructions?: string | null;
    requested_model?: string | null;
    provider_session_id?: string | null;
    provider_work_dir?: string | null;
  };
}

export interface OwnerAgentRunAcceptedFrame extends WSFrame {
  type: 'owner_agent_run_accepted';
  payload: OwnerAgentRunPayloadBase & {
    host_id: string;
    accepted_at?: string;
  };
}

export interface OwnerAgentRunEventFrame extends WSFrame {
  type: 'owner_agent_run_event';
  payload: OwnerAgentRunPayloadBase & {
    seq: number;
    event_type: OwnerAgentWsRunEventType;
    content?: string;
    metadata?: Record<string, unknown>;
  };
}

export interface OwnerAgentRunCompletedFrame extends WSFrame {
  type: 'owner_agent_run_completed';
  payload: OwnerAgentRunPayloadBase & {
    seq: number;
    final_message?: string;
    actual_model?: string | null;
    provider_session_id?: string | null;
    provider_work_dir?: string | null;
  };
}

export interface OwnerAgentRunFailedFrame extends WSFrame {
  type: 'owner_agent_run_failed';
  payload: OwnerAgentRunPayloadBase & {
    seq: number;
    error_code: string;
    error_message: string;
    retryable?: boolean;
  };
}

export interface OwnerAgentRunCancelFrame extends WSFrame {
  type: 'owner_agent_run_cancel';
  payload: OwnerAgentRunPayloadBase & {
    reason?: string;
    requested_by: 'owner' | 'gateway';
  };
}

// ─── Unions ──────────────────────────────────────────────────────────

export type ClientFrame =
  | PingFrame
  | VisitorMessageFrame
  | AgentMessageFrame
  | StreamChunkFrame
  | StreamEndFrame
  | ReadReceiptFrame
  | AuthFrame
  | HostRegisterFrame
  | HostHeartbeatFrame
  | HostCapabilitiesUpdatedFrame
  | OwnerAgentRunAcceptedFrame
  | OwnerAgentRunEventFrame
  | OwnerAgentRunCompletedFrame
  | OwnerAgentRunFailedFrame;

export type ServerFrame =
  | ConnectionAckFrame
  | AckFrame
  | MessageFrame
  | VisitorMessageBroadcastFrame
  | AgentTypingFrame
  | StreamChunkFrame
  | StreamEndFrame
  | PongFrame
  | ErrorFrame
  | SystemFrame
  | OwnerAgentRunRequestFrame
  | OwnerAgentRunEventFrame
  | OwnerAgentRunCompletedFrame
  | OwnerAgentRunFailedFrame
  | OwnerAgentRunCancelFrame;

// Frame type discriminator — list of all valid `type` values the gateway
// Zod layer will accept on inbound traffic. Kept here so non-Zod consumers
// (web) can still do exhaustive narrowing.
export const INBOUND_FRAME_TYPES = [
  'ping',
  'visitor_message',
  'agent_message',
  'stream_chunk',
  'stream_end',
  'read_receipt',
  'auth',
  'host_register',
  'host_heartbeat',
  'host_capabilities_updated',
  'owner_agent_run_accepted',
  'owner_agent_run_event',
  'owner_agent_run_completed',
  'owner_agent_run_failed',
] as const;

export type InboundFrameType = (typeof INBOUND_FRAME_TYPES)[number];

// Outbound (gateway → client) frame type discriminator — symmetric
// counterpart to `INBOUND_FRAME_TYPES`. Lives here (not in
// `ws/outbound.ts`) so non-Zod consumers can do exhaustive narrowing
// without pulling in zod. Source of truth for both
// `outbound.ts.outboundSchemaMap` keys and `validateOutboundFrame`
// dispatch.
export const OUTBOUND_FRAME_TYPES = [
  'connection_ack',
  'ack',
  'message',
  'agent_typing',
  'pong',
  'error',
  'system',
  'stream_chunk',
  'stream_end',
  'visitor_message',
  'owner_agent_run_request',
  'owner_agent_run_event',
  'owner_agent_run_completed',
  'owner_agent_run_failed',
  'owner_agent_run_cancel',
] as const;

export type OutboundFrameType = (typeof OUTBOUND_FRAME_TYPES)[number];
