import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, mkdirSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const SCRIPT = path.join(REPO_ROOT, 'scripts/sync-contracts.mjs');

function runScript(
  args: string[],
  cwd: string
): { status: number; stdout: string; stderr: string } {
  try {
    const stdout = execFileSync('node', [SCRIPT, ...args], {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: 0, stdout, stderr: '' };
  } catch (err) {
    const e = err as { status: number; stdout?: Buffer; stderr?: Buffer };
    return {
      status: e.status ?? 1,
      stdout: e.stdout?.toString() ?? '',
      stderr: e.stderr?.toString() ?? '',
    };
  }
}

describe('sync-contracts.mjs', () => {
  let sandbox: string;

  beforeEach(() => {
    sandbox = mkdtempSync(path.join(tmpdir(), 'qrclaw-sync-'));
    mkdirSync(path.join(sandbox, 'shared/contracts/ws'), { recursive: true });
    mkdirSync(path.join(sandbox, 'shared/contracts/http/decrypted-messages'), {
      recursive: true,
    });
    mkdirSync(path.join(sandbox, 'supabase/functions/_shared'), { recursive: true });
    writeFileSync(
      path.join(sandbox, 'shared/contracts/ws/types.ts'),
      '// source of truth\nexport type Foo = "bar";\n'
    );
    // M3-T3: http/decrypted-messages/types.ts is also a sync entry — sandbox
    // must provide it or the script exits 2 ("source missing") for that line.
    writeFileSync(
      path.join(sandbox, 'shared/contracts/http/decrypted-messages/types.ts'),
      '// http decrypted-messages types\nexport type Dm = "ok";\n'
    );
  });

  afterEach(() => {
    rmSync(sandbox, { recursive: true, force: true });
  });

  it('copies shared/contracts/ws/types.ts to supabase/_shared/contracts/ws/types.ts', () => {
    const result = runScript([], sandbox);
    expect(result.status).toBe(0);
    const dest = path.join(sandbox, 'supabase/functions/_shared/contracts/ws/types.ts');
    expect(existsSync(dest)).toBe(true);
    const copied = readFileSync(dest, 'utf8');
    expect(copied).toContain('export type Foo = "bar"');
    expect(copied).toMatch(/generated by scripts\/sync-contracts\.mjs/i);
  });

  it('copies http/decrypted-messages/types.ts to supabase/_shared mirror', () => {
    const result = runScript([], sandbox);
    expect(result.status).toBe(0);
    const dest = path.join(
      sandbox,
      'supabase/functions/_shared/contracts/http/decrypted-messages/types.ts'
    );
    expect(existsSync(dest)).toBe(true);
    const copied = readFileSync(dest, 'utf8');
    expect(copied).toContain('export type Dm = "ok"');
    expect(copied).toMatch(/generated by scripts\/sync-contracts\.mjs/i);
    // Header must name the source so humans editing the mirror know to touch the original.
    expect(copied).toContain('shared/contracts/http/decrypted-messages/types.ts');
  });

  it('--check exits 0 when destination matches source', () => {
    runScript([], sandbox);
    const result = runScript(['--check'], sandbox);
    expect(result.status).toBe(0);
  });

  it('--check exits non-zero and prints diff hint when destination is stale', () => {
    runScript([], sandbox);
    writeFileSync(
      path.join(sandbox, 'shared/contracts/ws/types.ts'),
      '// source of truth v2\nexport type Foo = "baz";\n'
    );
    const result = runScript(['--check'], sandbox);
    expect(result.status).not.toBe(0);
    expect(result.stderr + result.stdout).toMatch(/out of sync|drift/i);
  });

  it('--check exits non-zero when destination is missing', () => {
    const result = runScript(['--check'], sandbox);
    expect(result.status).not.toBe(0);
  });
});
