#!/usr/bin/env bash
# setup-local-env.sh — 从 ~/.config/qrclaw/secrets.env 生成 gateway/.env 和 web/.env.local
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS=${QRCLAW_SECRETS:-$HOME/.config/qrclaw/secrets.env}

log() { printf '\033[1;36m[setup-env]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[setup-env:err]\033[0m %s\n' "$*" >&2; exit 1; }

[[ -r "$SECRETS" ]] || die "找不到密钥文件: $SECRETS（见 docs/local-dev-secrets.md）"
# shellcheck disable=SC1090
source "$SECRETS"

for var in SUPABASE_URL SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY WS_TICKET_SECRET QRCLAW_KEK_V1 QRCLAW_HOST_TOKEN_PEPPER; do
  [[ -n "${!var:-}" ]] || die "secrets.env 缺少 $var"
done

GATEWAY_ENV="$REPO_ROOT/gateway/.env"
WEB_ENV="$REPO_ROOT/web/.env.local"
LOCAL_GATEWAY_PORT=${GATEWAY_PORT:-3100}

cat >"$GATEWAY_ENV" <<EOF
# Generated by scripts/setup-local-env.sh — do not commit
PORT=${LOCAL_GATEWAY_PORT}
HOST=0.0.0.0
NODE_ENV=development
CORS_ORIGIN=http://localhost:3000
REDIS_URL=redis://localhost:6379
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
WS_TICKET_SECRET=${WS_TICKET_SECRET}
QRCLAW_KEK_V1=${QRCLAW_KEK_V1}
QRCLAW_HOST_TOKEN_PEPPER=${QRCLAW_HOST_TOKEN_PEPPER}
GATEWAY_BASE_URL=http://127.0.0.1:${LOCAL_GATEWAY_PORT}
EOF
chmod 600 "$GATEWAY_ENV"
log "wrote $GATEWAY_ENV"

cat >"$WEB_ENV" <<EOF
# Generated by scripts/setup-local-env.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
NEXT_PUBLIC_GATEWAY_URL=http://127.0.0.1:${LOCAL_GATEWAY_PORT}
NEXT_PUBLIC_GATEWAY_WS_URL=ws://127.0.0.1:${LOCAL_GATEWAY_PORT}/ws
NEXT_PUBLIC_LOCAL_DEV=1
NEXT_PUBLIC_LOCAL_DEV_EMAIL=local-dev@localhost
NEXT_PUBLIC_LOCAL_DEV_PASSWORD=LocalDev-Only-9x!
LOCAL_DEV_BOOTSTRAP=1
LOCAL_DEV_EMAIL=local-dev@localhost
LOCAL_DEV_PASSWORD=LocalDev-Only-9x!
EOF
chmod 600 "$WEB_ENV"
log "wrote $WEB_ENV"
log "done — run: bash scripts/dev-up.sh"
